// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CreateQuery</b><br>
 * Generated     : <b>2011/07/25 1:22:51 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  July 25, 2011
 * @author swatjain
 */
public abstract class CreateQueryHelper extends RationalTestScript
{
	/**
	 * AddAttributeCondition: with default state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition"));
	}
	/**
	 * AddAttributeCondition: with specific test context and state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition"), anchor, flags);
	}
	
	/**
	 * AddAttributeCondition: with default state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition2"));
	}
	/**
	 * AddAttributeCondition: with specific test context and state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition2"), anchor, flags);
	}
	
	/**
	 * AddAttributeCondition: with default state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition3"));
	}
	/**
	 * AddAttributeCondition: with specific test context and state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition3"), anchor, flags);
	}
	
	/**
	 * AddAttributeCondition: with default state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition4"));
	}
	/**
	 * AddAttributeCondition: with specific test context and state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition4"), anchor, flags);
	}
	
	/**
	 * AddAttributeCondition: with default state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition5() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition5"));
	}
	/**
	 * AddAttributeCondition: with specific test context and state.
	 *		.text : Add attribute condition
	 * 		.id : dijit_form_Button_1
	 * 		.title : 
	 * 		.dojoclass : button
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAttributeCondition5(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAttributeCondition5"), anchor, flags);
	}
	
	/**
	 * LogInsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"));
	}
	/**
	 * LogInsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"), anchor, flags);
	}
	
	/**
	 * Runsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_runsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_runsubmit"));
	}
	/**
	 * Runsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_runsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_runsubmit"), anchor, flags);
	}
	
	/**
	 * Savesubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject button_savesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_savesubmit"));
	}
	/**
	 * Savesubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject button_savesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_savesubmit"), anchor, flags);
	}
	
	/**
	 * currentUseron: with default state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : currentUser
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_currentUseron() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_currentUseron"));
	}
	/**
	 * currentUseron: with specific test context and state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : currentUser
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_currentUseron(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_currentUseron"), anchor, flags);
	}
	
	/**
	 * stateon: with default state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : state
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_stateon() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_stateon"));
	}
	/**
	 * stateon: with specific test context and state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : state
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_stateon(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_stateon"), anchor, flags);
	}
	
	/**
	 * QueryNewQueryChangeAndConfigurationManagement: with default state.
	 *		.title : Query: New Query - Change and Configuration Management
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/Rational%20Functiona ...
	 */
	protected DocumentTestObject document_queryNewQueryChangeAn() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_queryNewQueryChangeAn"));
	}
	/**
	 * QueryNewQueryChangeAndConfigurationManagement: with specific test context and state.
	 *		.title : Query: New Query - Change and Configuration Management
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/Rational%20Functiona ...
	 */
	protected DocumentTestObject document_queryNewQueryChangeAn(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_queryNewQueryChangeAn"), anchor, flags);
	}
	
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_Attribute: with default state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_AttributeChooser_0
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web"));
	}
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_Attribute: with specific test context and state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_AttributeChooser_0
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web"), anchor, flags);
	}
	
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with default state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_19
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 19
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web2"));
	}
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with specific test context and state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_19
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 19
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web2"), anchor, flags);
	}
	
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with default state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_20
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 20
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web3"));
	}
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with specific test context and state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_20
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 20
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web3"), anchor, flags);
	}
	
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_Attribute: with default state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_AttributeChooser_0
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web4"));
	}
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_Attribute: with specific test context and state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_AttributeChooser_0
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web4"), anchor, flags);
	}
	
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with default state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_29
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 29
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web5() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web5"));
	}
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with specific test context and state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_29
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 29
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web5(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web5"), anchor, flags);
	}
	
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_Attribute: with default state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_AttributeChooser_0
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 3
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web6() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web6"));
	}
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_Attribute: with specific test context and state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_AttributeChooser_0
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 3
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web6(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web6"), anchor, flags);
	}
	
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with default state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_73
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 73
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web7() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web7"));
	}
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with specific test context and state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_73
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 73
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web7(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web7"), anchor, flags);
	}
	
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with default state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_75
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 75
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web8() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web8"));
	}
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_: with specific test context and state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_queryeditor_IconItem_75
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 75
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web8(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web8"), anchor, flags);
	}
	
	/**
	 * jazz_ui_internal_ImgMenuItem_8_text: with default state.
	 *		.id : jazz_ui_internal_ImgMenuItem_8_text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_jazz_ui_internal_ImgMenuI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_jazz_ui_internal_ImgMenuI"));
	}
	/**
	 * jazz_ui_internal_ImgMenuItem_8_text: with specific test context and state.
	 *		.id : jazz_ui_internal_ImgMenuItem_8_text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_jazz_ui_internal_ImgMenuI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_jazz_ui_internal_ImgMenuI"), anchor, flags);
	}
	
	/**
	 * AddCondition: with default state.
	 *		.text : Add Condition
	 * 		.href : #
	 * 		.id : 
	 * 		.title : Add Condition
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addCondition() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addCondition"));
	}
	/**
	 * AddCondition: with specific test context and state.
	 *		.text : Add Condition
	 * 		.href : #
	 * 		.id : 
	 * 		.title : Add Condition
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addCondition(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addCondition"), anchor, flags);
	}
	
	/**
	 * is: with default state.
	 *		.text : is
	 * 		.href : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_is() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_is"));
	}
	/**
	 * is: with specific test context and state.
	 *		.text : is
	 * 		.href : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_is(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_is"), anchor, flags);
	}
	
	/**
	 * is: with default state.
	 *		.text : is
	 * 		.href : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_is2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_is2"));
	}
	/**
	 * is: with specific test context and state.
	 *		.text : is
	 * 		.href : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_is2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_is2"), anchor, flags);
	}
	
	/**
	 * jazz_ui_MenuPopup_2: with default state.
	 *		.text : Work Items
	 * 		.href : #action=jazz.viewPage&id=com.ibm.team.workitem
	 * 		.id : jazz_ui_MenuPopup_2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_jazz_ui_MenuPopup_2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_jazz_ui_MenuPopup_2"));
	}
	/**
	 * jazz_ui_MenuPopup_2: with specific test context and state.
	 *		.text : Work Items
	 * 		.href : #action=jazz.viewPage&id=com.ibm.team.workitem
	 * 		.id : jazz_ui_MenuPopup_2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_jazz_ui_MenuPopup_2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_jazz_ui_MenuPopup_2"), anchor, flags);
	}
	
	/**
	 * jazz_ui_ResourceLink_0: with default state.
	 *		.text : Rational Functional Tester
	 * 		.href : /jazz/web/projects/Rational%20Functional%20Tester
	 * 		.id : jazz_ui_ResourceLink_0
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_jazz_ui_ResourceLink_0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_jazz_ui_ResourceLink_0"));
	}
	/**
	 * jazz_ui_ResourceLink_0: with specific test context and state.
	 *		.text : Rational Functional Tester
	 * 		.href : /jazz/web/projects/Rational%20Functional%20Tester
	 * 		.id : jazz_ui_ResourceLink_0
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_jazz_ui_ResourceLink_0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_jazz_ui_ResourceLink_0"), anchor, flags);
	}
	
	/**
	 * _81810181028103811811181128113828: with default state.
	 *		.text : 8.1 8.1.0.1 8.1.0.2 8.1.0.3 8.1.1 8.1.1.1 8.1.1.2 8.1.1.3 8.2 8.2.0.1 8.2.0.1 iF ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list__818101810281038118111811() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list__818101810281038118111811"));
	}
	/**
	 * _81810181028103811811181128113828: with specific test context and state.
	 *		.text : 8.1 8.1.0.1 8.1.0.2 8.1.0.3 8.1.1 8.1.1.1 8.1.1.2 8.1.1.3 8.2 8.2.0.1 8.2.0.1 iF ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list__818101810281038118111811(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list__818101810281038118111811"), anchor, flags);
	}
	
	/**
	 * UnclassifiedS4MinorS3NormalS2MajorS1CriticalS1Blocker: with default state.
	 *		.text : Unclassified S4-Minor S3-Normal S2-Major S1-Critical S1-Blocker
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_unclassifiedS4MinorS3Norm() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_unclassifiedS4MinorS3Norm"));
	}
	/**
	 * UnclassifiedS4MinorS3NormalS2MajorS1CriticalS1Blocker: with specific test context and state.
	 *		.text : Unclassified S4-Minor S3-Normal S2-Major S1-Critical S1-Blocker
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_unclassifiedS4MinorS3Norm(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_unclassifiedS4MinorS3Norm"), anchor, flags);
	}
	
	/**
	 * dijit_Menu_2: with default state.
	 *		.id : dijit_Menu_2
	 * 		.title : 
	 * 		.dojoclass : menu
	 * 		.class : Html.TABLE
	 */
	protected DojoMenuTestObject menu_dijit_Menu_2() 
	{
		return new DojoMenuTestObject(
                        getMappedTestObject("menu_dijit_Menu_2"));
	}
	/**
	 * dijit_Menu_2: with specific test context and state.
	 *		.id : dijit_Menu_2
	 * 		.title : 
	 * 		.dojoclass : menu
	 * 		.class : Html.TABLE
	 */
	protected DojoMenuTestObject menu_dijit_Menu_2(TestObject anchor, long flags) 
	{
		return new DojoMenuTestObject(
                        getMappedTestObject("menu_dijit_Menu_2"), anchor, flags);
	}
	
	/**
	 * dijit_Menu_5: with default state.
	 *		.id : dijit_Menu_5
	 * 		.title : 
	 * 		.dojoclass : menu
	 * 		.class : Html.TABLE
	 */
	protected DojoMenuTestObject menu_dijit_Menu_5() 
	{
		return new DojoMenuTestObject(
                        getMappedTestObject("menu_dijit_Menu_5"));
	}
	/**
	 * dijit_Menu_5: with specific test context and state.
	 *		.id : dijit_Menu_5
	 * 		.title : 
	 * 		.dojoclass : menu
	 * 		.class : Html.TABLE
	 */
	protected DojoMenuTestObject menu_dijit_Menu_5(TestObject anchor, long flags) 
	{
		return new DojoMenuTestObject(
                        getMappedTestObject("menu_dijit_Menu_5"), anchor, flags);
	}
	
	/**
	 * nowabsolute: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : absolute
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : now
	 * 		.classIndex : 3
	 */
	protected ToggleGUITestObject radioButton_nowabsolute() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_nowabsolute"));
	}
	/**
	 * nowabsolute: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : absolute
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : now
	 * 		.classIndex : 3
	 */
	protected ToggleGUITestObject radioButton_nowabsolute(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_nowabsolute"), anchor, flags);
	}
	
	/**
	 * TypeIdSummaryOwnedByStatusPrioritySeverityModifiedDateActions: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_typeIdSummaryOwnedByStat() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_typeIdSummaryOwnedByStat"));
	}
	/**
	 * TypeIdSummaryOwnedByStatusPrioritySeverityModifiedDateActions: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_typeIdSummaryOwnedByStat(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_typeIdSummaryOwnedByStat"), anchor, flags);
	}
	
	/**
	 * HtmlINPUTText: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_htmlINPUTText() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_htmlINPUTText"));
	}
	/**
	 * HtmlINPUTText: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_htmlINPUTText(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_htmlINPUTText"), anchor, flags);
	}
	
	/**
	 * j_password: with default state.
	 *		.id : jazz_app_internal_LoginWidget_0_password
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"));
	}
	/**
	 * j_password: with specific test context and state.
	 *		.id : jazz_app_internal_LoginWidget_0_password
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"), anchor, flags);
	}
	
	/**
	 * j_username: with default state.
	 *		.id : jazz_app_internal_LoginWidget_0_userId
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.INPUT
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"));
	}
	/**
	 * j_username: with specific test context and state.
	 *		.id : jazz_app_internal_LoginWidget_0_userId
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.INPUT
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"), anchor, flags);
	}
	
	/**
	 * widget_dijit_form_DateTextBox_0: with default state.
	 *		.id : widget_dijit_form_DateTextBox_0
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_widget_dijit_form_DateTex() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_widget_dijit_form_DateTex"));
	}
	/**
	 * widget_dijit_form_DateTextBox_0: with specific test context and state.
	 *		.id : widget_dijit_form_DateTextBox_0
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_widget_dijit_form_DateTex(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_widget_dijit_form_DateTex"), anchor, flags);
	}
	
	

	protected CreateQueryHelper()
	{
		setScriptName("CreateQuery");
	}
	
}

