// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CreateDefect</b><br>
 * Generated     : <b>2011/07/25 12:58:19 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  July 25, 2011
 * @author swatjain
 */
public abstract class CreateDefectHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * AddAndClosesubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAndClosesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAndClosesubmit"));
	}
	/**
	 * AddAndClosesubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addAndClosesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addAndClosesubmit"), anchor, flags);
	}
	
	/**
	 * LogInsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"));
	}
	/**
	 * LogInsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"), anchor, flags);
	}
	
	/**
	 * Savesubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_savesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_savesubmit"));
	}
	/**
	 * Savesubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_savesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_savesubmit"), anchor, flags);
	}
	
	/**
	 * NewWorkItemChangeAndConfigurationManagement: with default state.
	 *		.title : New Work Item - Change and Configuration Management
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/Rational%20Functiona ...
	 */
	protected DocumentTestObject document_newWorkItemChangeAndC() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_newWorkItemChangeAndC"));
	}
	/**
	 * NewWorkItemChangeAndConfigurationManagement: with specific test context and state.
	 *		.title : New Work Item - Change and Configuration Management
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/Rational%20Functiona ...
	 */
	protected DocumentTestObject document_newWorkItemChangeAndC(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_newWorkItemChangeAndC"), anchor, flags);
	}
	
	/**
	 * NewWorkItemChangeAndConfigurationManagement: with default state.
	 *		.title : New Work Item - Change and Configuration Management
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/Rational%20Functiona ...
	 */
	protected DocumentTestObject document_newWorkItemChangeAndC2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_newWorkItemChangeAndC2"));
	}
	/**
	 * NewWorkItemChangeAndConfigurationManagement: with specific test context and state.
	 *		.title : New Work Item - Change and Configuration Management
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://jazzop19.rtp.raleigh.ibm.com:9443/jazz/web/projects/Rational%20Functiona ...
	 */
	protected DocumentTestObject document_newWorkItemChangeAndC2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_newWorkItemChangeAndC2"), anchor, flags);
	}
	
	/**
	 * FolderView: with default state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject folderViewtable() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("folderViewtable"));
	}
	/**
	 * FolderView: with specific test context and state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject folderViewtable(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("folderViewtable"), anchor, flags);
	}
	
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_layout_SectionLayout_: with default state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_layout_SectionLayout_5
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web"));
	}
	/**
	 * com_ibm_team_workitem_web_ui_internal_view_layout_SectionLayout_: with specific test context and state.
	 *		.id : com_ibm_team_workitem_web_ui_internal_view_layout_SectionLayout_5
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_com_ibm_team_workitem_web(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_com_ibm_team_workitem_web"), anchor, flags);
	}
	
	/**
	 * jazz_ui_internal_ImgMenuItem_9_text: with default state.
	 *		.id : jazz_ui_internal_ImgMenuItem_9_text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_jazz_ui_internal_ImgMenuI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_jazz_ui_internal_ImgMenuI"));
	}
	/**
	 * jazz_ui_internal_ImgMenuItem_9_text: with specific test context and state.
	 *		.id : jazz_ui_internal_ImgMenuItem_9_text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_jazz_ui_internal_ImgMenuI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_jazz_ui_internal_ImgMenuI"), anchor, flags);
	}
	
	/**
	 * uploadFileInput: with default state.
	 *		.text : 
	 * 		.id : 
	 * 		.type : file
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.file
	 * 		.name : uploadFileInput
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_uploadFileInput() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_uploadFileInput"));
	}
	/**
	 * uploadFileInput: with specific test context and state.
	 *		.text : 
	 * 		.id : 
	 * 		.type : file
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.file
	 * 		.name : uploadFileInput
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_uploadFileInput(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_uploadFileInput"), anchor, flags);
	}
	
	/**
	 * AddToSubscribedByList: with default state.
	 *		.text : Add...
	 * 		.href : #
	 * 		.id : 
	 * 		.title : Add to Subscribed By List...
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addToSubscribedByList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addToSubscribedByList"));
	}
	/**
	 * AddToSubscribedByList: with specific test context and state.
	 *		.text : Add...
	 * 		.href : #
	 * 		.id : 
	 * 		.title : Add to Subscribed By List...
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addToSubscribedByList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addToSubscribedByList"), anchor, flags);
	}
	
	/**
	 * jazz_ui_MenuPopup_2: with default state.
	 *		.text : Work Items
	 * 		.href : #action=jazz.viewPage&id=com.ibm.team.workitem
	 * 		.id : jazz_ui_MenuPopup_2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_jazz_ui_MenuPopup_2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_jazz_ui_MenuPopup_2"));
	}
	/**
	 * jazz_ui_MenuPopup_2: with specific test context and state.
	 *		.text : Work Items
	 * 		.href : #action=jazz.viewPage&id=com.ibm.team.workitem
	 * 		.id : jazz_ui_MenuPopup_2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_jazz_ui_MenuPopup_2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_jazz_ui_MenuPopup_2"), anchor, flags);
	}
	
	/**
	 * jazz_ui_ResourceLink_0: with default state.
	 *		.text : Rational Functional Tester
	 * 		.href : /jazz/web/projects/Rational%20Functional%20Tester
	 * 		.id : jazz_ui_ResourceLink_0
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_jazz_ui_ResourceLink_0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_jazz_ui_ResourceLink_0"));
	}
	/**
	 * jazz_ui_ResourceLink_0: with specific test context and state.
	 *		.text : Rational Functional Tester
	 * 		.href : /jazz/web/projects/Rational%20Functional%20Tester
	 * 		.id : jazz_ui_ResourceLink_0
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_jazz_ui_ResourceLink_0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_jazz_ui_ResourceLink_0"), anchor, flags);
	}
	
	/**
	 * Links: with default state.
	 *		.text : Links
	 * 		.href : #action=com.ibm.team.workitem.newWorkItem&ts=13112308090000&tab=links
	 * 		.id : 
	 * 		.title : Links
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_links() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_links"));
	}
	/**
	 * Links: with specific test context and state.
	 *		.text : Links
	 * 		.href : #action=com.ibm.team.workitem.newWorkItem&ts=13112308090000&tab=links
	 * 		.id : 
	 * 		.title : Links
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_links(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_links"), anchor, flags);
	}
	
	/**
	 * owner: with default state.
	 *		.text : Unassigned AMIT VAID Ashish K. Mathur Aswani K. Thunga1 BALAJI SRINIVASAN Clemen ...
	 * 		.id : owner
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_owner() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_owner"));
	}
	/**
	 * owner: with specific test context and state.
	 *		.text : Unassigned AMIT VAID Ashish K. Mathur Aswani K. Thunga1 BALAJI SRINIVASAN Clemen ...
	 * 		.id : owner
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_owner(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_owner"), anchor, flags);
	}
	
	/**
	 * UnassignedCustomerUseInternalCustomerUseExternalDevel: with default state.
	 *		.text : Unassigned Customer Use (Internal) Customer Use (External) Development Functiona ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_unassignedCustomerUseInte() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_unassignedCustomerUseInte"));
	}
	/**
	 * UnassignedCustomerUseInternalCustomerUseExternalDevel: with specific test context and state.
	 *		.text : Unassigned Customer Use (Internal) Customer Use (External) Development Functiona ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_unassignedCustomerUseInte(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_unassignedCustomerUseInte"), anchor, flags);
	}
	
	/**
	 * UnassignedP3LowP2MediumP1High: with default state.
	 *		.text : Unassigned P3-Low P2-Medium P1-High
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_unassignedP3LowP2MediumP1() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_unassignedP3LowP2MediumP1"));
	}
	/**
	 * UnassignedP3LowP2MediumP1High: with specific test context and state.
	 *		.text : Unassigned P3-Low P2-Medium P1-High
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_unassignedP3LowP2MediumP1(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_unassignedP3LowP2MediumP1"), anchor, flags);
	}
	
	/**
	 * UnclassifiedS4MinorS3NormalS2MajorS1CriticalS1Blocker: with default state.
	 *		.text : Unclassified S4-Minor S3-Normal S2-Major S1-Critical S1-Blocker
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_unclassifiedS4MinorS3Norm() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_unclassifiedS4MinorS3Norm"));
	}
	/**
	 * UnclassifiedS4MinorS3NormalS2MajorS1CriticalS1Blocker: with specific test context and state.
	 *		.text : Unclassified S4-Minor S3-Normal S2-Major S1-Critical S1-Blocker
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_unclassifiedS4MinorS3Norm(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_unclassifiedS4MinorS3Norm"), anchor, flags);
	}
	
	/**
	 * Open: with default state.
	 *		.text : Open
	 * 		.class : .Pushbutton
	 * 		.name : Open
	 * 		.classIndex : 0
	 */
	protected GuiTestObject openbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("openbutton"));
	}
	/**
	 * Open: with specific test context and state.
	 *		.text : Open
	 * 		.class : .Pushbutton
	 * 		.name : Open
	 * 		.classIndex : 0
	 */
	protected GuiTestObject openbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("openbutton"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * IDNameSizeCreatedByDate: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idNameSizeCreatedByDate() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idNameSizeCreatedByDate"));
	}
	/**
	 * IDNameSizeCreatedByDate: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idNameSizeCreatedByDate(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idNameSizeCreatedByDate"), anchor, flags);
	}
	
	/**
	 * HtmlINPUTText: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_htmlINPUTText() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_htmlINPUTText"));
	}
	/**
	 * HtmlINPUTText: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_htmlINPUTText(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_htmlINPUTText"), anchor, flags);
	}
	
	/**
	 * HtmlINPUTText: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_htmlINPUTText2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_htmlINPUTText2"));
	}
	/**
	 * HtmlINPUTText: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_htmlINPUTText2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_htmlINPUTText2"), anchor, flags);
	}
	
	/**
	 * j_password: with default state.
	 *		.id : jazz_app_internal_LoginWidget_0_password
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"));
	}
	/**
	 * j_password: with specific test context and state.
	 *		.id : jazz_app_internal_LoginWidget_0_password
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"), anchor, flags);
	}
	
	/**
	 * j_username: with default state.
	 *		.id : jazz_app_internal_LoginWidget_0_userId
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.INPUT
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"));
	}
	/**
	 * j_username: with specific test context and state.
	 *		.id : jazz_app_internal_LoginWidget_0_userId
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.INPUT
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"), anchor, flags);
	}
	
	/**
	 * widget_dijit_form_DateTextBox_0: with default state.
	 *		.id : widget_dijit_form_DateTextBox_0
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_widget_dijit_form_DateTex() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_widget_dijit_form_DateTex"));
	}
	/**
	 * widget_dijit_form_DateTextBox_0: with specific test context and state.
	 *		.id : widget_dijit_form_DateTextBox_0
	 * 		.title : 
	 * 		.dojoclass : textbox
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_widget_dijit_form_DateTex(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_widget_dijit_form_DateTex"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point com_ibm_team_workitem_web_ui_i_standard object in the SUT.
	 */
	protected IFtVerificationPoint com_ibm_team_workitem_web_ui_i_standardVP() 
	{
		return vp("com_ibm_team_workitem_web_ui_i_standard");
	}
	protected IFtVerificationPoint com_ibm_team_workitem_web_ui_i_standardVP(TestObject anchor)
	{
		return vp("com_ibm_team_workitem_web_ui_i_standard", anchor);
	}
	
	

	protected CreateDefectHelper()
	{
		setScriptName("CreateDefect");
	}
	
}

